# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Haoyu (Tony) Chen/Personal Homepage"
title_separator          : "-"
name                     : &name "Haoyu (Tony) Chen"
description              : &description "Research Assistant at Carnegie Mellon University"
url                      : https://tonychen050400.github.io 
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Tonychen050400/Tonychen050400.github.io"
